version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: testUsername
      POSTGRES_PASSWORD: testPassword
      POSTGRES_DB: testDatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  kafka:
    build:
      context: .
      dockerfile: ./kafka/Dockerfile
    hostname: localhost
    ports:
      - "34045:34045"
    container_name: kafka

  producer:
    build:
      context: .
      dockerfile: ./producer/Dockerfile
    container_name: producer
    depends_on:
      - kafka
      - postgres

  consumer:
    build:
      context: .
      dockerfile: ./consumer/Dockerfile
    container_name: consumer
    depends_on:
      - kafka
      - postgres
    tty: true
    stdin_open: true

volumes:
  pgdata:
