postgres.host=postgres
postgres.port=5432
postgres.database=testDatabase
postgres.username=testUsername
postgres.password=testPassword
#
kafka.brokers=1
kafka.partitions=1
kafka.topic.events=events
#
sql.events.create=CREATE TABLE events (id SERIAL PRIMARY KEY, key VARCHAR(255), value TEXT, timestamp BIGINT, topic VARCHAR(255), partition INT, "offset" BIGINT);
sql.events.insert=INSERT INTO events (key, value, timestamp, topic, partition, "offset") VALUES (?, ?, ?, ?, ?, ?);
sql.events.select=SELECT key, value, timestamp, topic, partition, "offset" FROM events;